from pathlib import Path
import re,json,zipfile
root = Path(__file__).resolve().parent
src = root / 'src'
out = root / 'docs'
out.mkdir(parents=True, exist_ok=True)
meta=[
('01','The story inside the data','Mean, median, and the shape of variation.','01-DataSummary.pdf','10qzlEP0KcW0O1Prun81YHoZrWd50y3OY',31,'25–35 minutes',[(1,12,'Center, loss functions, geometry, outliers'),(13,22,'Spread, range, quantiles, IQR, diamonds, boxplots'),(23,31,'Variance, standard deviation, notation, empirical rule, practice')]),
('02','A language for uncertainty','Sample spaces, events, and the rules that keep probability consistent.','02-Probability-Part1.pdf','1hRhUQHsHpt8Iltyr2HL3YMRuVfV3KgrR',43,'25–35 minutes',[(1,17,'Deterministic and stochastic models; sample spaces; dice, needles, and chords'),(18,38,'Events, set operations, subsets, partitions, and De Morgan’s laws'),(39,43,'Probability axioms, equally likely outcomes, cars, and dice')]),
('03','Count without counting twice','Build outcomes, keep the distinctions that matter, and remove duplicates.','03-Counting.pdf','1g8DMAIb3UVqBzOcX4A4H_SstuVx6vB92',53,'30–45 minutes',[(1,8,'Probability review and equally likely sample spaces'),(9,24,'Sum and product rules; permutations; books, plates, pipelines, officers'),(25,33,'Combinations, binomial theorem, repetition, and multisets'),(34,51,'Lotto and every poker-hand category'),(52,53,'Coin-toss counting and the tournament bridge')]),
('04','Find the easier question','Complements, symmetry, collisions, and inclusion–exclusion.','04-Probability-Part2.pdf','1UZS4g0hVz42I1jnsBmiKRB3jGzCkfyfw',36,'30–45 minutes',[(1,4,'Tournament symmetry and intersecting chords'),(5,16,'Complements, lottery, occupancy, birthdays, repeated letters'),(17,30,'Addition rules, overlap proofs, host cities, and bridge hands'),(31,36,'Many events, dice coverage, digit runs, divisibility, derangements, no-repeat words')]),
('05','Let evidence change your mind','Conditioning, independence, Bayes, prediction, and gambler’s ruin.','05-Probability-Part3.pdf','10BdvgFEaR7wI0MJX8QDlAH44GlTS59Xs',44,'40–55 minutes',[(1,13,'Conditional probability, subscriptions, independence, coin counterexample, fox tags'),(14,22,'Multiplication rule, urns, total probability, and sports model'),(23,30,'Bayes derivation, detector example, and general updating'),(31,36,'Unknown urn, posterior prediction, and fraud exercise'),(37,44,'Random-walk context and both gambler’s-ruin derivations')]),
('06','Turn chance into a number','Random variables, mass, density, cumulative probability, and mixed models.','06-RandomVariables.pdf','1nzYAnJSMFWGW9uvUu8u-0zVoHzasxwWI',36,'35–50 minutes',[(1,9,'Random-variable mappings, dependent clicks, stopping, and dice PMFs'),(10,25,'CDFs, densities, unit-square geometry, and differentiation'),(26,32,'Mixed spending, discrete endpoints, and CDF properties'),(33,36,'Infinite PMF normalization, unusual dice, and lottery net gain')])]
css=(src/'style.css').read_text();js=(src/'interactive.js').read_text()
def slug(m):return m[0]+'-'+['data','foundations','counting','probability-rules','evidence','random-variables'][int(m[0])-1]+'.html'
def doc(title,body):return '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><link rel="icon" href="data:,"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Six intuitive interactive lessons based on STAT 5701 probability and statistics slides."><title>'+title+' · Probability, understood</title><style>'+css+'</style></head><body>'+body+'<script>'+js+'</script></body></html>'
def header():return '<header><a class="brand" href="index.html">Probability, understood</a><div class="header-tools"><a href="index.html">All six lessons</a><button data-print>Print lesson</button></div></header>'
manifest=[]
for i,m in enumerate(meta):
 num,title,desc,pdf,id,pages,time,ranges=m;content=(src/(num+'.html')).read_text();content=content.replace('<table>','<div class="table-wrap"><table>').replace('</table>','</table></div>');heads=re.findall(r'<section class="chapter" id="(.*?)">.*?<h2>(.*?)</h2>',content,re.S)
 nav='<aside><nav aria-label="Course navigation"><p class="eyebrow">Your six-lesson path</p>'+''.join(f'<a href="{slug(x)}" class="{"active" if x==m else ""}"'+(' aria-current="page"' if x==m else '')+f'>{x[0]} · {x[1]}</a>' for x in meta)+'<div class="toc-local"><p class="eyebrow" style="margin-top:30px">In this lesson</p>'+''.join(f'<a href="#{anchor}">{re.sub("<.*?>","",h)}</a>' for anchor,h in heads)+'<a href="#source">Slide coverage &amp; sources</a></div></nav></aside>'
 hero=f'<div class="hero"><p class="eyebrow">Lesson {num} / 06 · STAT 5701 companion</p><h1>{title}</h1><p class="deck">{desc}</p><p class="meta">Suggested pace: {time} with experiments · Based on {pages} PDF pages</p></div>'
 coverage='<section class="chapter source" id="source"><p class="eyebrow">Source &amp; coverage</p><h2>Return to the slides.</h2><p>This lesson is an original teaching companion to <a href="https://drive.google.com/file/d/'+id+'/view" target="_blank" rel="noopener">'+pdf+'</a> in your Probability &amp; Statistics folder (STAT 5701, Dobrin Marchev). Page references below use PDF page positions, which may differ from printed slide numbers.</p><ul>'+''.join(f'<li><strong>PDF pages {a}–{b}:</strong> {topic}.</li>' for a,b,topic in ranges)+'</ul><p>The main narrative develops the concepts; expandable sections hold additional derivations and slide exercises. New analogies, interactive experiments, and precision notes supplement the slides. Source errors are corrected explicitly where they affect answers. All diagrams are newly drawn.</p></section>'
 nxt='<div class="next">'+(f'<a href="{slug(meta[i-1])}">← Lesson {i}</a>' if i else '<a href="index.html">← Course home</a>')+(f'<a href="{slug(meta[i+1])}">Continue to lesson {i+2} →</a>' if i<5 else '<a href="index.html">Back to the complete course →</a>')+'</div>'
 body=header()+'<div class="shell">'+nav+'<main>'+hero+content+coverage+nxt+'</main></div>'
 (out/slug(m)).write_text(doc(title,body));manifest.append({'lesson':num,'title':title,'file':slug(m),'source_pdf':pdf,'source_id':id,'pages_reviewed':pages,'labs':content.count('data-lab='),'checks':content.count('class="quiz"'),'words_approx':len(re.sub('<[^>]+>',' ',content).split())})
hero='<div class="hero"><p class="eyebrow">A visual field guide · Six lessons</p><h1>Probability starts<br>making sense.</h1><p class="deck">Build the ideas from the ground up. See them move. Learn why the formulas have to look the way they do.</p><p>Prepared for Sai from all six PDFs in your Probability &amp; Statistics folder. Each lesson follows its corresponding slide deck, with a story to follow, experiments to explore, and worked practice to return to.</p><div class="route"><span>Describe data</span><span>Define possibilities</span><span>Count</span><span>Combine events</span><span>Use evidence</span><span>Build distributions</span></div></div>'
cards='<div class="course-grid">'+''.join(f'<a class="course-card" href="{slug(m)}"><span class="eyebrow">Lesson {m[0]} · {m[5]} source pages</span><h2>{m[1]}</h2><p>{m[2]}</p><span class="small">{m[6]} &nbsp; →</span></a>' for m in meta)+'</div>'
intro='<div class="callout"><strong>A way to study that makes the ideas stick</strong><p>Read the story. Before touching a slider, predict what will change. Explain what you see in your own words. Attempt the questions before opening worked solutions. Tomorrow, reconstruct each lesson’s memory picture without looking.</p></div><p class="small">All six lessons work offline in a browser, including the diagrams and experiments. Links back to Google Drive require internet access. Use “Print lesson” for a reading copy with worked solutions expanded. Random simulations vary; exact probabilities are labeled separately. Displayed decimals are rounded. Estimated study times include experiments and selected exercises.</p><div class="memory"><h3>243 pages, connected into one progression.</h3><p>Thirteen interactive experiments. Thirteen concept checks with explanations. Step-by-step proofs and a worked exercise bank. Source-page coverage in every lesson.</p></div>'
(out/'index.html').write_text(doc('Six lessons',header()+'<main class="landing">'+hero+cards+intro+'</main>'))
(out/'README.txt').write_text('PROBABILITY, UNDERSTOOD\n\nOpen index.html in any modern browser. Six numbered HTML files are the six lessons. Each lesson is self-contained and works offline; source links need internet.\n\nStudy method: predict, experiment, explain, attempt the checks, then open solutions. Revisit the memory picture the following day.\n\nBased on 243 pages across the six STAT 5701 PDFs in the connected Probability & Statistics Google Drive folder. References use PDF page positions. This is an original companion, not an official course publication.\n\nAll interactions run locally. No account, installation, external library, or network connection is needed for the lessons. Print lesson expands worked solutions for printing.\n')
(out/'coverage.json').write_text(json.dumps(manifest,indent=2))
(out / '.nojekyll').touch()
with zipfile.ZipFile(out.parent/'probability-lessons.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in out.iterdir():z.write(f,'probability-lessons/'+f.name)
print(json.dumps(manifest,indent=2));print('Total words',sum(x['words_approx'] for x in manifest),'labs',sum(x['labs'] for x in manifest),'checks',sum(x['checks'] for x in manifest))
