'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=(x,d=3)=>Number(x.toFixed(d)).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=(x,d=2)=>(100*x).toFixed(d)+'%';
const fact=n=>{let a=1;for(let j=2;j<=n;j++)a*=j;return a};
const choose=(n,k)=>{if(k<0||k>n)return 0;k=Math.min(k,n-k);let count=1;for(let j=1;j<=k;j++)count=count*(n-k+j)/j;return Math.round(count)};
const C={teal:'#006b68',gold:'#b44d20',blue:'#335c9e',light:'#e0f0e9',line:'#d4ded7',ink:'#183039'};
const el=(tag,attrs={},content='')=>`<${tag} ${Object.entries(attrs).map(([k,v])=>`${k}="${v}"`).join(' ')}>${content}</${tag}>`;
const text=(x,y,t,attrs={})=>el('text',{x,y,...attrs},t);
function svgBox(node,title,height,draw){const w=Math.max(250,Math.round(node.getBoundingClientRect().width));node.innerHTML=el('svg',{viewBox:`0 0 ${w} ${height}`,role:'img','aria-label':title},el('title',{},title)+draw(w,height));}
function plot(node,{title,xLabel,yLabel,xMin=0,xMax=1,yMin=0,yMax=1,lines=[],bars=[],xTicks=null,yTicks=null,points=[],dots=[]}){
 svgBox(node,title,280,(w,h)=>{let left=48,right=18,top=42,bottom=58;let X=x=>left+(x-xMin)/(xMax-xMin)*(w-left-right),Y=y=>h-bottom-(y-yMin)/(yMax-yMin)*(h-top-bottom);let out=text(12,19,yLabel,{'font-weight':650});
 const xt=xTicks||[xMin,(xMin+xMax)/2,xMax],yt=yTicks||[yMin,(yMin+yMax)/2,yMax];
 yt.forEach(y=>{out+=el('line',{x1:left,x2:w-right,y1:Y(y),y2:Y(y),class:'grid'})+text(left-7,Y(y)+4,fmt(y,2),{'text-anchor':'end'})});
 xt.forEach(x=>out+=text(X(x),h-bottom+24,fmt(x,2),{'text-anchor':x===xMin?'start':x===xMax?'end':'middle'}));
 out+=text((left+w-right)/2,h-9,xLabel,{'text-anchor':'middle'});
 bars.forEach(b=>{let bw=Math.max(2,(w-left-right)/(xMax-xMin)*(.65));out+=el('rect',{x:X(b.x)-bw/2,y:Y(b.y),width:bw,height:Math.max(0,Y(0)-Y(b.y)),fill:b.color||C.teal,opacity:b.dim?.28:1})});
 lines.forEach(l=>out+=el('path',{d:l.data.map((p,i)=>(i?'L':'M')+X(p[0])+','+Y(p[1])).join(' '),fill:'none',stroke:l.color||C.teal,'stroke-width':2.6,...(l.dashed?{'stroke-dasharray':'5 4'}:{})}));
 points.forEach(p=>out+=el('circle',{cx:X(p.x),cy:Y(p.y),r:5,fill:p.color||C.gold,stroke:'white','stroke-width':1.5}));
 dots.forEach(p=>out+=el('circle',{cx:X(p.x),cy:Y(p.y),r:3.5,fill:p.open?'#fffefb':p.color||C.teal,stroke:p.color||C.teal,'stroke-width':1.5}));return out;});
}
function birthday(n){let q=1;for(let j=0;j<n;j++)q*=Math.max(0,(365-j)/365);return 1-q}
function ruin(i,p,k=20){return Math.abs(p-.5)<1e-10?i/k:(1-((1-p)/p)**i)/(1-((1-p)/p)**k)}
function squareCDF(r){if(r<=0)return 0;if(r<=1)return Math.PI*r*r/4;if(r>=Math.SQRT2)return 1;return Math.sqrt(r*r-1)+r*r*(Math.PI/4-Math.acos(1/r))}
function mixedCDF(x){return x<0?0:x<=2?.4+.15*x*x:1}
function dicePMF(a,b){let m=new Map();for(let x of a)for(let y of b)m.set(x+y,(m.get(x+y)||0)+1);return [...m].sort((a,b)=>a[0]-b[0]).map(([x,n])=>({x,p:n/(a.length*b.length),n}))}
const standardDice=dicePMF([1,2,3,4,5,6],[1,2,3,4,5,6]);const oddDice=dicePMF([1,2,2,3,3,4],[1,3,4,5,6,8]);
const labs={
center(root,state){let z=+state.outlier,c=+state.candidate,a=[3,6,z],m=(9+z)/3;let sse=a.reduce((s,x)=>s+(x-c)**2,0),sae=a.reduce((s,x)=>s+Math.abs(x-c),0);svgBox($('[data-chart=center]',root),'Waiting times, mean, median and chosen center on a common 0 to 60 minute scale',240,(w,h)=>{let X=x=>28+x/60*(w-60);let out=el('line',{x1:X(0),x2:X(60),y1:74,y2:74,stroke:C.line});[0,15,30,45,60].forEach(x=>out+=text(X(x),103,x,{'text-anchor':'middle'}));a.forEach(x=>out+=el('circle',{cx:X(x),cy:74,r:7,fill:C.teal}));out+=text(28,22,'Observed waits (minutes)',{'font-weight':650});[['Mean',m,139,C.gold],['Median',6,176,C.teal],['Your c',c,213,C.blue]].forEach(([label,x,y,color])=>{out+=el('line',{x1:X(x),x2:X(x),y1:52,y2:92,stroke:color,'stroke-dasharray':'3 4'});out+=el('rect',{x:28,y:y-15,width:9,height:16,fill:color})+text(45,y,`${label}: ${fmt(x,2)} min`)});return out});$('.readout',root).innerHTML=`Data: 3, 6, ${z}. <strong>Mean ${fmt(m,2)}; median 6.</strong><br>At c=${fmt(c,1)}: squared error = ${fmt(sse,2)}; absolute error = ${fmt(sae,2)}. Minimum squared error occurs at ${fmt(m,2)}; minimum absolute error at 6.`;},
box(root,state){let a=state.diamond==='mixed'?[416,1429,1899,2537,8979,2209,1497]:[416,1416,1882,2497,3154,1924,703];svgBox($('[data-chart=box]',root),'Five-number summary of diamond prices on a common 0 to 9000 dollar scale',215,(w,h)=>{let X=x=>22+x/9000*(w-40);let out=text(22,22,'Diamond price ($)',{'font-weight':650});out+=el('line',{x1:X(a[0]),x2:X(a[4]),y1:85,y2:85,stroke:C.teal,'stroke-width':2});out+=el('rect',{x:X(a[1]),y:58,width:X(a[3])-X(a[1]),height:54,fill:C.light,stroke:C.teal});[a[0],a[2],a[4]].forEach(x=>out+=el('line',{x1:X(x),x2:X(x),y1:56,y2:115,stroke:C.teal,'stroke-width':2}));[0,3000,6000,9000].forEach(x=>out+=text(X(x),151,fmt(x),{'text-anchor':x===0?'start':x===9000?'end':'middle'}));out+=text(22,189,(w<400?'Box: Q1–Q3; line: median':'Line inside box = median; box = Q1 to Q3'));return out});$('.readout',root).innerHTML=`Min $${a[0]} · Q1 $${a[1]} · Median $${a[2]} · Q3 $${a[3]} · Max $${a[4]}<br><strong>IQR $${a[3]-a[1]} · Range $${a[4]-a[0]}</strong><br>Mean $${a[5]} · Sample SD $${a[6]}. Endpoints are actual min/max.`;},
'dice-events'(root,state){let test={high:(i,j)=>i+j>=10,seven:(i,j)=>i+j===7,double:(i,j)=>i===j,six:(i,j)=>i===6||j===6,bothsix:(i,j)=>i===6&&j===6}[state.event],count=0;let out='';for(let i=1;i<=6;i++)for(let j=1;j<=6;j++){let hit=test(i,j);count+=hit;out+=`<span class="token ${hit?'hit':'dim'}" aria-label="First die ${i}, second die ${j}, ${hit?'in':'outside'} event">${i},${j}${hit?' ✓':''}</span>`} $('[data-grid]',root).innerHTML=out;$('.readout',root).innerHTML=`<strong>${count} of 36 outcomes</strong> satisfy the event. Probability = ${count}/36 = ${pct(count/36)}. ✓ marks included outcomes.`;},
sets(root,state){let test={union:x=>x%2===0||x<4,intersect:x=>x%2===0&&x<4,complement:x=>x%2===1,demorgan:x=>!(x%2===0||x<4),difference:x=>x%2===0&&x>=4}[state.setop];let hits=[1,2,3,4,5,6].filter(test);$('[data-grid]',root).innerHTML=[1,2,3,4,5,6].map(x=>`<span class="token ${test(x)?'hit':'dim'}">${x}${test(x)?' ✓':''}</span>`).join('');$('.readout',root).innerHTML=`Selected set: {${hits.join(', ')}}. For a fair die, P = ${hits.length}/6. ✓ marks included outcomes.`;},
counting(root,state){let n=+state.n,r=+state.r,ordered=state.order==='ordered',all=[];function gen(arr){if(arr.length===r){all.push(arr.map(x=>String.fromCharCode(65+x)).join(ordered?' → ':' '));return}for(let j=0;j<n;j++)if(!arr.includes(j)&&(ordered||!arr.length||j>arr[arr.length-1]))gen([...arr,j])}gen([]);$('[data-grid]',root).innerHTML=all.slice(0,24).map(x=>`<span class="token">${ordered?x:'{ '+x+' }'}</span>`).join('');$('.readout',root).innerHTML=`<strong>${all.length} ${ordered?'role assignments':'teams'}</strong>. P(${n},${r})=${fact(n)/fact(n-r)} and C(${n},${r})=${choose(n,r)}.<br>Each team has ${r}!=${fact(r)} orderings.${all.length>24?' Showing the first 24 only.':' Every outcome is shown.'}`;},
birthday(root,state){let n=+state.people,p=birthday(n);plot($('[data-chart=birthday]',root),{title:'Exact probability of at least one shared birthday as room size changes',xLabel:'People in the room',yLabel:'Probability of a shared birthday',xMin:2,xMax:80,yMax:1,xTicks:[2,23,50,80],lines:[{data:Array.from({length:79},(_,i)=>[i+2,birthday(i+2)])},{data:[[2,.5],[80,.5]],color:C.gold,dashed:true}],points:[{x:n,y:p}]});let sim=root._sim&&root._sim.n===n?`<br>Simulation: ${root._sim.hits}/1,000 rooms had a match (${pct(root._sim.hits/1000)}). A fresh random sample will vary.`:'';$('.readout',root).innerHTML=`With ${n} people, <strong>exact P = ${pct(p,4)}</strong>. There are ${choose(n,2)} possible pairs. The dashed line marks 50%.${sim}`;},
inclusion(root,state){let m=+state.membership,s=+state.stage,a=m,b=s>=2?choose(m,2):0,c=s>=3?choose(m,3):0;svgBox($('[data-chart=inclusion]',root),'Number of copies contributed by individual events, pair overlaps, and triple overlap',200,(w,h)=>{let out='';[[a,'Add singles',C.teal],[-b,'Subtract pairs',C.gold],[c,'Add triple',C.blue]].forEach(([v,l,col],i)=>{let y=45+i*50;out+=text(12,y,l)+text(w-12,y,(v>=0?'+':'')+v,{'text-anchor':'end','font-weight':750});for(let j=0;j<Math.abs(v);j++)out+=el('circle',{cx:w*.57+j*24,cy:y-5,r:7,fill:col})});return out});$('.readout',root).innerHTML=`Stage ${s}: ${a} − ${b} + ${c} = <strong>${a-b+c} ${a-b+c===1?'copy':'copies'}</strong>. ${s===3?(m?'The outcome is counted exactly once.':'The outcome is outside the union and gets zero.'):m===3&&s===2?'The triple overlap vanished. Add it back in stage 3.':'Continue to the final stage to check the union weight.'}`;},
independence(root,state){let seq=Array.from({length:16},(_,n)=>n.toString(2).padStart(4,'0').replaceAll('0','T').replaceAll('1','H'));let check=s=>({A:s[0]===s[1],B:[...s].filter(x=>x==='H').length%2===1,C:s[2]===s[3]});let hit=s=>[...state.coinEvent].every(k=>check(s)[k]);let count=seq.filter(hit).length;$('[data-grid]',root).innerHTML=seq.map(s=>`<span class="token ${hit(s)?'hit':'dim'}">${s}${hit(s)?' ✓':''}</span>`).join('');$('.readout',root).innerHTML=`<strong>${count}/16 = ${fmt(count/16,4)}</strong>. Product of individual probabilities for this selection: (1/2)<sup>${state.coinEvent.length}</sup> = ${fmt(.5**state.coinEvent.length,4)}. ${state.coinEvent==='ABC'?'The triple fails the independence test.':'For this selection the product rule holds.'}`;},
bayes(root,state){let p=+state.prior/100,se=+state.sensitivity/100,fp=+state.falsepos/100,N=100000,t=N*p*se,f=N*(1-p)*fp,post=t/(t+f);svgBox($('[data-chart=bayes]',root),'Expected positive results per 100000: true positives and false positives',235,(w,h)=>{let max=Math.max(t,f,1),out=text(12,22,'Expected counts per 100,000',{'font-weight':650});[[t,'True positives',C.teal],[f,'False positives',C.gold]].forEach(([v,l,col],i)=>{let y=65+i*74;out+=text(12,y,l)+text(w-12,y,fmt(v,1),{'text-anchor':'end'});out+=el('rect',{x:12,y:y+10,width:(w-24)*v/max,height:23,fill:col})});return out});$('.readout',root).innerHTML=`<strong>P(target present | positive) = ${pct(post,4)}</strong><br>True positives ${fmt(t,1)} ÷ all positives ${fmt(t+f,1)}. Negative cases are excluded from this denominator. These are expected counts, which may be fractional.`;},
ruin(root,state){let p=+state.winp,i=+state.fortune,prob=ruin(i,p);plot($('[data-chart=ruin]',root),{title:'Exact probability of reaching 20 before zero versus starting fortune',xLabel:'Starting fortune ($)',yLabel:'Probability of reaching $20',xMin:0,xMax:20,yMax:1,xTicks:[0,5,10,15,20],lines:[{data:Array.from({length:21},(_,j)=>[j,ruin(j,p)])},{data:[[0,0],[20,1]],color:C.blue,dashed:true}],points:[{x:i,y:prob}]});let walk=root._walk;if(walk&&(walk.p!==p||walk.i!==i)){root._walk=null;walk=null}$('.readout',root).innerHTML=`From $${i}, with p=${p.toFixed(2)}, <strong>P(reach $20) ≈ ${pct(prob,3)}</strong>. Dashed line: fair-game baseline.${walk?'<br>'+walk.message:''}`;let node=$('[data-chart=walk]',root);if(walk){node.hidden=false;plot(node,{title:'One simulated gambler fortune path',xLabel:'Round number',yLabel:'Fortune ($)',xMax:Math.max(1,walk.data.length-1),yMax:20,yTicks:[0,10,20],lines:[{data:walk.data,color:C.gold}]})}else{node.hidden=true;node.innerHTML=''}},
distribution(root,state){let d=state.model==='dice'?standardDice:state.model==='odd-dice'?oddDice:[{x:3,p:.3},{x:5,p:.2},{x:8,p:.3},{x:10,p:.2}],t=+state.threshold,F=d.filter(v=>v.x<=t).reduce((s,v)=>s+v.p,0),mass=d.find(v=>v.x===t)?.p||0;plot($('[data-chart=pmf]',root),{title:'Probability mass at each value, with values at or below the selected threshold highlighted',xLabel:'Value x',yLabel:'Mass p(x)',xMin:0,xMax:13,yMax:.35,yTicks:[0,.15,.3],xTicks:[0,3,6,9,12],bars:d.map(v=>({x:v.x,y:v.p,dim:v.x>t}))});let sum=0,pts=[[0,0]],dots=[];for(let v of d){pts.push([v.x,sum]);dots.push({x:v.x,y:sum,open:true});sum+=v.p;pts.push([v.x,sum]);dots.push({x:v.x,y:sum})}pts.push([13,1]);plot($('[data-chart=cdf]',root),{title:'Right-continuous cumulative distribution, open circles exclude left limits and filled circles include values',xLabel:'Threshold x',yLabel:'Cumulative F(x)',xMin:0,xMax:13,yMax:1,xTicks:[0,3,6,9,12],lines:[{data:pts}],dots,points:[{x:t,y:F}]});$('.readout',root).innerHTML=`At t=${t}, <strong>F(t)=P(X≤t)=${fmt(F,5)}</strong>. Point mass P(X=t)=${fmt(mass,5)}.<br>Filled circles include the jump value; open circles mark excluded left limits. Pale bars are above the threshold.`;},
square(root,state){let r=+state.radius,F=squareCDF(r);svgBox($('[data-chart=square]',root),'Unit square shaded where distance from lower-left corner is at most the chosen radius',325,(w,h)=>{let side=Math.min(w-75,240),left=(w-side)/2,bottom=278,top=bottom-side;let out=el('defs',{},el('clipPath',{id:'squareclip'},el('rect',{x:left,y:top,width:side,height:side})));out+=el('rect',{x:left,y:top,width:side,height:side,fill:'#f2f3ed',stroke:C.ink});out+=el('circle',{cx:left,cy:bottom,r:r*side,fill:C.light,stroke:C.teal,'stroke-width':2,'clip-path':'url(#squareclip)'});out+=el('line',{x1:left,y1:bottom,x2:left+Math.min(r,1)*side,y2:bottom,stroke:C.gold,'stroke-width':3});out+=text(left-10,bottom+22,'(0,0)',{'text-anchor':'middle'})+text(left+side,top-12,'(1,1)',{'text-anchor':'end'})+text(left+side/2,315,'u coordinate; square side = 1',{'text-anchor':'middle'})+text(12,20,'Shaded area = F(r)',{'font-weight':650});return out});$('.readout',root).innerHTML=`r=${r.toFixed(2)}: <strong>F(r)=${fmt(F,5)} (${pct(F)})</strong>. ${r<=1?'The quarter-circle fits inside the square.':r<Math.SQRT2?'The square clips two caps of the quarter-circle.':'The radius reaches every point; F(r)=1.'}`;},
mixed(root,state){let x=+state.spend,F=mixedCDF(x),line=[[-.5,0],[0,0],[0,.4],...Array.from({length:100},(_,j)=>{let v=(j+1)/50;return[v,mixedCDF(v)]}),[2.5,1]];plot($('[data-chart=mixed]',root),{title:'Mixed distribution CDF: jump of 0.4 at zero, then continuous growth to one',xLabel:'Spending x (hundreds of dollars)',yLabel:'Cumulative F(x)',xMin:-.5,xMax:2.5,yMax:1,xTicks:[-.5,0,1,2,2.5],lines:[{data:line}],dots:[{x:0,y:0,open:true},{x:0,y:.4}],points:[{x,y:F}]});$('.readout',root).innerHTML=`Threshold $${fmt(x*100,0)}: <strong>P(X≤x)=${pct(F,2)}</strong>.<br>${x<0?'Spending is nonnegative, so no probability has accumulated.':x===0?'The entire 40% mass at zero is included immediately.':x<2?'Accumulated probability = 40% non-paying users plus the continuous area up to x.':'All spending outcomes are included.'}`;}
};
function setup(root){const state={};function read(){for(const e of $$('[data-k]',root)){state[e.dataset.k]=e.value;let o=$(`[data-v="${e.dataset.k}"]`,root);if(o)o.textContent=e.value}}function draw(){read();labs[root.dataset.lab](root,state)}root.addEventListener('input',draw);root.addEventListener('change',draw);root.addEventListener('click',e=>{let a=e.target.dataset.action;if(a==='rooms'){let n=+state.people,hits=0;for(let k=0;k<1000;k++){let days=new Set();let match=false;for(let j=0;j<n;j++){let d=Math.floor(Math.random()*365);if(days.has(d))match=true;days.add(d)}hits+=match}root._sim={n,hits};draw()}if(a==='walk'){let p=+state.winp,i=+state.fortune,x=i,data=[[0,x]],steps=0;while(x>0&&x<20&&steps<10000){x+=Math.random()<p?1:-1;data.push([++steps,x])}root._walk={p,i,data,message:x===0?`This game reached zero after ${steps} rounds.`:x===20?`This game reached $20 after ${steps} rounds.`:`This sample stopped displaying after 10,000 rounds without absorption; it is not counted as a win or loss.`};draw()}});draw();let lastWidth=0;new ResizeObserver(entries=>{let w=Math.round(entries[0].contentRect.width);if(w!==lastWidth){lastWidth=w;draw()}}).observe(root)}
$$('[data-lab]').forEach(setup);
$$('.quiz').forEach(q=>{$$('.options button',q).forEach((b,i)=>{b.addEventListener('click',()=>{let ok=i===+q.dataset.answer;$$('.options button',q).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('.feedback',q).textContent=(ok?'Correct. ':'Not quite. ')+q.dataset.explain})})});
const printButton=$('[data-print]');if(printButton)printButton.addEventListener('click',()=>{const details=$$('details'),before=details.map(d=>d.open);details.forEach(d=>d.open=true);const restore=()=>details.forEach((d,i)=>d.open=before[i]);window.addEventListener('afterprint',restore,{once:true});window.print()});
window.CourseMath={birthday,ruin,squareCDF,mixedCDF,dicePMF,choose};
function revealLinkedSection(){
 let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{return}
 if(!id)return;
 const target=document.getElementById(id);if(!target)return;
 let panel=target.matches('details')?target:target.closest('details');
 while(panel){panel.open=true;panel=panel.parentElement?.closest('details')}
 requestAnimationFrame(()=>target.scrollIntoView({block:'start'}));
}
window.addEventListener('hashchange',revealLinkedSection);
revealLinkedSection();
